Upgrade to latest boto3
Fixes this error when running `cloudmapper.py collect`:

> botocore.exceptions.InvalidConfigError: The profile "production" is
> configured to use SSO but is missing required configuration:
> sso_start_url, sso_region